config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :projects do
    resources :events do
      resources :registrations, only: [ :new, :create, :edit, :update, :destroy ]
    end
  end
  get '/registrations', to: 'pages#registrations', as: 'user_registrations'
  get '/volunteers', to: 'pages#volunteers', as: 'volunteers'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :project
  has_many :registrations, dependent: :destroy
  has_one_attached :photo
  validates :project, presence: true
  validates :date, presence: true
  validates :location, presence: true
  # validates :activity, presence: true, length: { maximum: 1000,
  #   too_long: "Massimo %{count} caratteri" }

  def datetime
    DateTime.parse(self.date)
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :events, dependent: :destroy
  has_one_attached :photo
  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 3000,
    too_long: "Massimo %{count} caratteri" }
  validates :photo, presence: true
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :user, presence: true
  validates :event, presence: true
  validates :note, length: { maximum: 1000,
    too_long: "Massimo %{count} caratteri" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :registrations, dependent: :destroy
  has_many :events, through: :registrations
  has_one_attached :photo
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :photo])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [ :show, :edit, :update, :destroy ]
  before_action :set_project

  def index
    @events = Event.where(project: @project)
  end

  def show
    @volunteers = User.all.select { |user| user.events.include?(@event) }
  end

  def new
    @project = Project.find(params[:project_id])
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.project = @project
    if @event.save
      create_more
      redirect_to project_events_path(@project)
    else
      render :new
    end
  end

  def create_more
    if @event.repeat == 'ogni settimana'
      event_date = DateTime.parse(params[:event][:date])
      end_date = params[:event][:end_date] == nil ? Date.today + 3.months : params[:event][:end_date]
      loop do
        event_date += 1.week
        break if event_date > Date.parse(end_date)
        event = Event.new(event_params)
        event.date = event_date
        event.project = @project
        event.save
      end
    elsif @event.repeat == 'ogni due settimane'
      event_date = DateTime.parse(params[:event][:date])
      end_date = params[:event][:end_date] == nil ? Date.today + 3.months : params[:event][:end_date]
      loop do
        event_date += 2.weeks
        break if event_date > Date.parse(end_date)
        event = Event.new(event_params)
        event.date = event_date
        event.project = @project
        event.save
      end
    elsif @event.repeat == 'ogni mese'
      event_date = DateTime.parse(params[:event][:date])
      end_date = params[:event][:end_date] == nil ? Date.today + 3.months : params[:event][:end_date]
      loop do
        event_date += 1.month
        break if event_date > Date.parse(end_date)
        event = Event.new(event_params)
        event.date = event_date
        event.project = @project
        event.save
      end
    end
  end

  def edit
  end

  def update
    url = Rails.application.routes.recognize_path(request.referrer)
    if url[:action] == 'show'
      @event.closed = params[:event][:closed] == "0" ? true : false
      @event.save
    else
      @event.update(event_params)
    end
    redirect_to project_event_path(@project, @event)
  end

  def destroy
    @event.destroy
    redirect_to project_events_path(@project)
  end

  private

  def event_params
    params.require(:event).permit(:date, :location, :activity, :closed, :information, :photo, :repeat, :end_date)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @projects = Project.all.select { |project| project.events.count > 0 }
  end

  def registrations
    @registrations = Registration.where(user_id: current_user.id)
  end

  def volunteers
    @volunteers = User.where(admin: false)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [ :show, :edit, :update, :destroy ]

  def index
    @projects = Project.all.select { |project| project.events.count > 0 }
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @projects = Project.all
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.save
    redirect_to projects_path
  end

  def edit
  end

  def update
    @project.update(project_params)
    redirect_to projects_path
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :photo)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :find_registration, only: [ :edit, :update, :destroy ]
  before_action :set_project
  before_action :set_event

  def new
    @registration = Registration.new
  end

  def create
    @registration = Registration.new(registration_params)
    @registration.user = current_user
    @registration.event = @event
    if @registration.save
      redirect_to user_registrations_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @registration.update(registration_params)
    redirect_to project_event_path(@project, @event)
  end

  def destroy
    @registration.destroy
    redirect_to user_registrations_path
  end

  private

  def registration_params
    params.require(:registration).permit(:note, :car)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def find_registration
    @registration = Registration.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<div class="form-event">
  <%= simple_form_for [ @project, @event ] do |f| %>
    <i class="fas fa-calendar-alt icon-blue"></i><%= f.input :date, input_html: {class: "datepicker bg-white", placeholder:"quando?"}, label: false, autofocus: true, required: true, error: 'Perfavore inserisci la data' %>
    <i class="fas fa-map-marker-alt icon-blue"></i><%= f.input :location, label: false, required: true, input_html: { placeholder:"dove?", class: "address-input", type: "search"} %>
    <i class="fas fa-users icon-blue"></i><%= f.input :activity, label: false, required: true, input_html: { placeholder:"attività"} %>
    <i class="fas fa-info-circle icon-blue"></i><%= f.input :information, label: false, required: true, input_html: { placeholder:"info"} %>
    <i class="fas fa-images icon-blue"></i><%= f.input :photo, as: :file, label: false, input_html: { placeholder:"foto", class: "photo-input"} %>
    <i class="fas fa-redo-alt"></i><%= f.input :repeat, label: false, collection: ['mai', 'ogni settimana', 'ogni due settimane', 'ogni mese'], selected: ['mai'], input_html: { placeholder:"ripeti"} %>
    <i class="fas fa-hourglass-end"></i><%= f.input :end_date, label: false, input_html: { placeholder:"ripeti fino al", class: "datepicker bg-white"} %>
    <%= f.submit class: "btn btn-warning btn-circle mt-3 mb-2", placeholder: "CREA EVENTO" %>
  <% end %>
</div>

app/views/events/edit.html.erb
<% if current_user.admin %>

  <div class="event-image-container bigger-event-image-container mb-4">
    <% if @project.photo.attached? %>
      <%= cl_image_tag @project.photo.key, class: 'blurred-banner' %>
    <% else %>
      <%= image_tag "https://res.cloudinary.com/chunhua/image/upload/v1610124765/sos-spesa_z5njbh.png", class: 'blurred-banner'%>
    <% end %>
    <div class="event-container event-container-form">
      <div class="event-info d-flex high">
        <% if @project.photo.attached? %>
          <%= cl_image_tag @project.photo.key, class: 'form-image' %>
        <% else %>
          <%= image_tag "https://res.cloudinary.com/chunhua/image/upload/v1610124765/sos-spesa_z5njbh.png", class: 'form-image'%>
        <% end %>
        <div class="p-4 event-highlights">
          <%= render "form" %>
        </div>
      </div>
      <div class="event-details-blue short p-4">
        <h1 class="paragraph-title-white"> <%= @project.name %></h1>
      </div>
    </div>
  </div>

<% end %>

app/views/events/index.html.erb
<% if current_user.admin %>

  <div class="banner d-flex align-items-end mb-4 ">
    <div class="container-content-banner container align-items-center d-flex justify-content-between">
      <h1 class='page-title'> <%= @project.name.upcase %></h1>
      <%= link_to edit_project_path(@project) do %>
        <p class="btn btn-light btn-lg fw-bold"> DETTAGLI PROGETTO </p>
      <% end %>
    </div>
  </div>
  <div class="container grid-container">
  <% if @events.count == 0 %>
      <%= link_to new_project_event_path(@project) do  %><div class="btn btn-warning btn-circle mt-3">CREA NUOVO EVENTO</div><% end %>
  <% end %>
    <% @events.each do |event| %>
    <div class="card event-card">
      <div class="card-body">
        <div class="d-flex">
          <div class="flex-grow-1">
            <h4 class="card-title"><%= event.datetime.strftime("%^a, %e %^b") %></h4>
            <p><i class="fas fa-clock"></i> <%= event.datetime.strftime("%H:%M") %></p>
            <p><i class="fas fa-map-marker-alt"></i> <%= event.location == nil ? "n/a" : event.location  %></p>
          </div>
          <div class="btn-container">
          <%= link_to project_event_path(@project, event) do %>
            <div class="btn btn-circle btn-warning"><i class="fas fa-external-link-square-alt"></i></div>
          <% end %>
          </div>
        </div>
        <div class="d-flex">
          <h6 class="fw-bold border-top border-warning pt-3"><%= event.activity == nil ? "n/a" : event.activity  %></h6>
        </div>
      </div>
    </div>
    <% end %>
  </div>

<% else %>
  <div class="banner d-flex align-items-end mb-4">
    <div class="container-content-banner container align-items-center d-flex justify-content-between">
      <h1 class='page-title'> <%= @project.name.upcase %></h1>
      <%= link_to "#" do %>
        <p class="btn btn-primary btn-lg fw-bold"> SCOPRI DI PIU' </p>
      <% end %>
    </div>
  </div>
  <div class="container grid-container">
    <% @events.each do |event| %>
    <div class="card event-card">
      <div class="card-body">
        <div class="d-flex">
          <div class="flex-grow-1">
            <h4 class="card-title"><%= event.datetime.strftime("%^a, %e %^b") %></h4>
            <p><i class="fas fa-clock"></i> <%= event.datetime.strftime("%H:%M") %></p>
            <p><i class="fas fa-map-marker-alt"></i> <%= event.location == nil ? "n/a" : event.location  %></p>
          </div>
          <div class="btn-container">
          <%= link_to new_project_event_registration_path(@project, event) do %>
            <div class="btn btn-circle btn-warning"><i class="fas fa-external-link-square-alt"></i></div>
          <% end %>
          </div>
        </div>
        <div class="d-flex">
          <h6 class="fw-bold border-top border-warning pt-3"><%= event.activity == nil ? "n/a" : event.activity  %></h6>
        </div>
      </div>
    </div>
    <% end %>
  </div>

<% end %>

app/views/events/new.html.erb
<% if current_user.admin %>

  <div class="event-image-container">
    <% if @project.photo.attached? %>
      <%= cl_image_tag @project.photo.key, class: 'blurred-banner' %>
    <% else %>
      <%= image_tag "https://res.cloudinary.com/chunhua/image/upload/v1610124765/sos-spesa_z5njbh.png", class: 'blurred-banner'%>
    <% end %>
    <div class="event-container event-container-form">
      <div class="event-info d-flex high">
        <% if @project.photo.attached? %>
          <%= cl_image_tag @project.photo.key, class: 'form-image' %>
        <% else %>
          <%= image_tag "https://res.cloudinary.com/chunhua/image/upload/v1610124765/sos-spesa_z5njbh.png", class: 'form-image'%>
        <% end %>
        <div class="p-4 event-highlights">
          <%= render "form" %>
        </div>
      </div>
      <div class="event-details-blue short p-4">
        <h1 class="paragraph-title-white"> <%= @project.name %></h1>
      </div>
    </div>
  </div>

<% end %>

app/views/events/show.html.erb
<% if current_user.admin %>
  <div class="event-image-container">
    <% if @event.project.photo.attached? %>
      <%= cl_image_tag @event.project.photo.key, class: 'blurred-banner'%>
    <% else %>
      <%= image_tag "https://res.cloudinary.com/chunhua/image/upload/v1610124765/sos-spesa_z5njbh.png", class: 'blurred-banner' %>
    <% end %>
    <div class="event-container event-container-smaller">
      <div class="event-info d-flex">
        <% if @event.photo.attached? %>
          <%= cl_image_tag @event.photo.key %>
        <% else %>
          <%= image_tag "https://res.cloudinary.com/chunhua/image/upload/v1610124765/sos-spesa_z5njbh.png"%>
        <% end %>
        <div class="p-4 event-highlights">
          <p style="font-weight: bold;"><i class="fas fa-calendar-alt"></i> <%= @event.datetime.strftime("%^a, %e %^b") %></p>
          <p><i class="fas fa-clock"></i> <%= @event.datetime.strftime("%H:%M") %></p>
          <p><i class="fas fa-map-marker-alt"></i> <%= @event.location == nil ? "n/a" : @event.location  %></p>
          <p><i class="fas fa-users"></i> <%= @event.registrations == nil ? 0 : @event.registrations.count %> volontari si sono <strong>registrati</strong></p>
          <br>
          <div class="d-flex justify-content-between event-icons align-items-center">
            <% if @event.closed %>
              <div class="btn btn-disabled btn-circle open-btn">RIAPRI ISCRIZIONI</div>
            <% else %>
              <div class="btn btn-warning btn-circle close-btn">CHIUDI ISCRIZIONI</div>
            <% end %>

            <div>
            <%= link_to edit_project_event_path(@project, @event) do %><i class="fas fa-edit" style="margin-right: 15px; color: #b5b5b5 !important;"></i><% end %><%= link_to project_event_path(@project, @event), method: :delete, data: { confirm: "Sei sicuro di voler eliminare l'evento?" } do %><i class="fas fa-trash"></i><% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="event-details d-flex p-4">
        <div class="project-specs p-4">
          <h1 class="paragraph-title"> <%= @event.project.name %></h1>
          <p><%= @event.project.description == nil ? "n/a" : @event.project.description  %></p>
        </div>
        <div class="event-specs p-4">
          <div class="orange-box border border-warning p-3">
            <p style="font-weight: bold;">ATTIVITA'</p>
            <p><%= @event.activity == nil ? "n/a" : @event.activity  %></p>
            <br>
            <p style="font-weight: bold;">INFORMAZIONI *</p>
            <p><%= @event.information == nil ? "n/a" : @event.information %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <% if @volunteers.count != 0 %>
    <h1 class="section-title-blue mb-4">Chi parteciperà?</h1>
    <% end %>
  <div class="grid-container">
    <% @volunteers.each do |volunteer| %>
    <div class="card registrations-card">
      <div class="card-body">
        <div class="d-flex">
          <div class="flex-grow-1">
            <h4 class="card-title"><%= volunteer.first_name.capitalize %> <%= volunteer.last_name.capitalize %></h4>
            <p><i class="fas fa-envelope"></i><a href="mailto:<%= volunteer.email %>" class="pl-2"><%= volunteer.email %></a></p>
            <p><i class="fas fa-phone-alt"></i><a href="num:<%= volunteer.phone_number %>" class="pl-2"><%= volunteer.phone_number %></a></p>
          </div>
          <div class="btn-container">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: 'avatar' %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/mvdallarosa", class: "avatar" %>
            <% end %>
          </div>
        </div>
        <div class="border-top border-success pt-3">
          <h6 style="font-weight: bold;">VOLONTARIO DA:</h6>
          <h6><%= volunteer.created_at.strftime("%e %b, %Y") %></h6>
          <h6 style="font-weight: bold; padding-top: 10px;">HA PARTECIPATO A:</h6>
          <h6><%= volunteer.registrations == nil ? 0 : volunteer.registrations.size %> eventi.</h6>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

  <div style="display: none;">
    <%= simple_form_for([@project, @event], :html=> { class: 'close-form' }) do |f| %>
      <%= f.input :closed, input_html: { class: 'close-input' } %>
      <%= f.button :submit %>
    <% end %>
  </div>

<% else %>
  <div class="event-image-container mb-4">
    <% if @event.project.photo.attached? %>
      <%= cl_image_tag @event.project.photo.key, class: 'blurred-banner'%>
    <% else %>
      <%= image_tag "https://res.cloudinary.com/chunhua/image/upload/v1610124765/sos-spesa_z5njbh.png", class: 'blurred-banner' %>
    <% end %>
    <div class="event-container event-container-smaller">
      <div class="event-info d-flex">
        <% if @event.photo.attached? %>
          <%= cl_image_tag @event.photo.key %>
        <% else %>
          <%= image_tag "https://res.cloudinary.com/chunhua/image/upload/v1610124765/sos-spesa_z5njbh.png"%>
        <% end %>
        <div class="p-4 event-highlights">
          <p style="font-weight: bold;"><i class="fas fa-calendar-alt"></i> <%= @event.datetime.strftime("%^a, %e %^b") %></p>
          <p><i class="fas fa-clock"></i> <%= @event.datetime.strftime("%H:%M") %></p>
          <p><i class="fas fa-map-marker-alt"></i> <%= @event.location == nil ? "n/a" : @event.location %></p>
          <% if @event.closed %>
            <div class="btn btn-disabled btn-circle mt-3 disabled">REGISTRAZIONI CHIUSE</div>
          <% else %>
            <%= link_to new_project_event_registration_path(@project, @event) do  %><div class="btn btn-warning btn-circle mt-3">PARTECIPA</div><% end %>
          <% end %>
        </div>
      </div>
      <div class="event-details d-flex p-4">
        <div class="project-specs p-4">
          <h1 class="paragraph-title"> <%= @event.project.name %></h1>
          <p><%= @event.project.description == nil ? "n/a" : @event.project.description  %></p>
        </div>
        <div class="event-specs p-4">
          <div class="orange-box border border-warning p-3">
            <p style="font-weight: bold;">ATTIVITA'</p>
            <p><%= @event.activity == nil ? "n/a" : @event.activity %></p>
            <br>
            <p style="font-weight: bold;">INFORMAZIONI *</p>
            <p><%= @event.information == nil ? "n/a" : @event.information  %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/registrations.html.erb
<div class="container mt-5">
  <h1 class="page-title">Eventi a cui parteciperò</h1>
  <div class="grid-container">
    <% @registrations.each do |registration| %>
    <div class="card registrations-card">
      <div class="card-body">
        <div class="d-flex">
          <div class="flex-grow-1">
            <h4 class="card-title"><%= registration.event.datetime.strftime("%^a, %e %^b") %></h4>
            <p><i class="fas fa-clock"></i> <%= registration.event.datetime.strftime("%H:%M") %></p>
            <p><i class="fas fa-map-marker-alt"></i> <%= registration.event.location == nil ? "n/a" : registration.event.location %></p>
          </div>
          <div class="btn-container">
          <%= link_to project_event_registration_path(registration.event.project, registration.event, registration), method: :delete, data: { confirm: "Sei sicuro di non voler più partecipare?" } do %>
            <div class="btn btn-circle btn-success"><i class="fas fa-times"></i></div>
          <% end %>
          </div>
        </div>
        <div class="border-top border-success pt-3">
          <h6 style="font-weight: bold;">PROGETTO</h6>
          <h6><%= registration.event.project.name %></h6>
          <h6 style="font-weight: bold; padding-top: 10px;">ATTIVITA'</h6>
          <h6><%= registration.event.activity == nil ? "n/a" : registration.event.activity %></h6>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/projects/edit.html.erb
<% if current_user.admin %>
<div class="container-blue form-project d-flex justify-content-between my-5">
  <h1 class="section-title">Vuoi modificare il progetto?</h1>
  <%= render "form" %>
</div>

<% end %>

app/views/projects/index.html.erb
<% if current_user.admin %>
  <div class="container mt-5">
    <% if Project.all.count == 0 %>
      <h1 class="page-title">Vuoi creare un nuovo progetto?</h1>
      <%= link_to new_project_path do  %><div class="btn btn-warning btn-circle mt-3">CREA</div><% end %>
    <% else %>
      <h1 class="page-title">Vuoi creare un evento per quale progetto?</h1>
      <div class="grid-container">
        <% Project.all.each do |project| %>
        <div class="card project-card">
          <% if project.photo.attached? %>
            <%= cl_image_tag project.photo.key, class: 'card-img-top' %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/chunhua/image/upload/v1610124765/sos-spesa_z5njbh.png", class: 'card-img-top' %>
          <% end %>
          <div class="card-body d-flex">
            <h3 class="card-title mr-2 flex-grow-1"><%= project.name.upcase %></h3>
            <%= link_to new_project_event_path(project) do %>
            <p><i class="fas fa-arrow-circle-right icon-small"></i></p>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="container mt-5">
    <h1 class="page-title">A quale progetto vorresti contribuire?</h1>
    <div class="grid-container">
      <% @projects.each do |project| %>
      <div class="card project-card">
        <% if project.photo.attached? %>
          <%= cl_image_tag project.photo.key, class: 'card-img-top' %>
        <% else %>
          <%= image_tag "https://res.cloudinary.com/chunhua/image/upload/v1610124765/sos-spesa_z5njbh.png", class: 'card-img-top' %>
        <% end %>
        <div class="card-body d-flex">
          <h3 class="card-title mr-2 flex-grow-1"><%= project.name.upcase %></h3>
          <%= link_to project_events_path(project) do %>
          <p><i class="fas fa-arrow-circle-right icon-small"></i></p>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-c sticky-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png", class: 'filter-darken' %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto pb-0">
      <% if user_signed_in? %>
        <% if current_user.admin %>
          <li class="nav-item">
            <%= link_to projects_path, class: "nav-link" do %> <i class="fas fa-plus-square icon-orange"></i> <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to "HOME", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "PROGETTI", new_project_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "VOLONTARI", volunteers_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: 'avatar avatar-admin dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/mvdallarosa", class: "avatar avatar-admin dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Modifica Profilo", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Esci", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "HOME", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "PROGETTI", projects_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a href="mailto:volontari@nph.org" class="nav-link">CONTATTACI</a>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: 'avatar dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/mvdallarosa", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Modifica Profilo", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Prossimi Appuntamenti", "/registrations", class: "dropdown-item" %>
              <%= link_to "Esci", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to "ACCEDI", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>